//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SuperCarros
{
    using System;
    using System.Collections.Generic;
    
    public partial class AddVehicle
    {
        public int Id { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Year { get; set; }
        public string Brand { get; set; }
        public string Model { get; set; }
        public string Engine { get; set; }
        public string Transmission { get; set; }
        public string Color { get; set; }
        public string Description { get; set; }
        public string Location { get; set; }
        public string Seller_Name { get; set; }
        public string Phone_Number { get; set; }
        public byte[] Picture { get; set; }
    }
}
